name: gha-tools
description: 'Installs gha-tools'

runs:
  using: composite
  steps:
    - name: Install python3.8, venv, pip on runner container
      run: sudo apt update -y && sudo apt install -y python3.8-venv python3-venv python3-pip
      shell: bash

    - name: Install pipx
      run: |
        python3 -m pip install pipx
        python3 -m pipx ensurepath --force
      shell: bash

    - name: Download and install gha-tools and friends
      run: |
        #wget https://github.com/rapidsai/gha-tools/releases/latest/download/tools.tar.gz -O - | sudo tar -xz -C /usr/local/bin
        git clone https://github.com/sevagh/gha-tools -b feat/wheel-build-num-autoincrement && sudo cp ./gha-tools/tools/* /usr/local/bin/
        pip install awscli twine
      shell: bash
