name: purewheel
description: 'Installs python3 and pip to build pure python wheels'
inputs:
  repo-dir:
    description: 'Path to repo dir'
    required: true
  package-dir:
    description: 'Path to python package relative to repo-dir'
    required: true
  output-dir:
    description: 'Path to output wheels'
    required: true
 
runs:
  using: composite
  steps:
    - name: Build wheel inside manylinux container
      run: >
        docker run
        -v "$(readlink -f ${{ inputs.repo-dir }}):/code-dir"
        -v "$(readlink -f ${{ inputs.output-dir }}):/out-dir"
        rapidsai/manylinux:amd64
        /opt/python/cp38-cp38/bin/python -m pip wheel -w /out-dir /code-dir/${{ inputs.package-dir }} --no-deps
      shell: bash
