name: "Wheel CTK name generator"
inputs:
  ctk:
    type: string
  package-name:
    type: string
outputs:
  rapids_py_cuda_suffix:
    value: ${{ steps.ctk-gen.outputs.RAPIDS_PY_WHEEL_CUDA_SUFFIX }}
  rapids_py_wheel_name:
    value: ${{ steps.ctk-gen.outputs.RAPIDS_PY_WHEEL_NAME }}

runs:
  using: composite
  steps:
    - name: Set CTK-related vars from input CTK versions
      id: ctk-gen
      shell: bash
      run: |
        ctk_tag="${{ inputs.ctk }}"
        ctk_major=$(echo $ctk_tag | cut -d'.' -f1)
        cuda_suffix="-cu${ctk_major}"
        wheelname="${{ inputs.package-name }}_cu${ctk_major}"

        echo "RAPIDS_PY_WHEEL_CUDA_SUFFIX=${cuda_suffix}" | tee --append "${GITHUB_ENV}" "${GITHUB_OUTPUT}"
        echo "RAPIDS_PY_WHEEL_NAME=${wheelname}" | tee --append "${GITHUB_ENV}" "${GITHUB_OUTPUT}"
