on:
  workflow_call:
    inputs:
      sha:
        type: string
      arch:
        type: string
        default: '["amd64"]'
      cuda:
        type: string
        default: '["12.0"]'
      python_package_manager:
        type: string
        default: '["conda", "pip"]'
      repo:
        type: string
      node_type:
        type: string
        default: "cpu8"
      build_command:
        type: string
        required: true
      # Note that this is the _name_ of a secret containing the key, not the key itself.
      extra-repo-deploy-key:
        required: false
        type: string
        default: ''
      # Note that this is the _name_ of a secret containing the key, not the key itself.
      extra-repo-deploy-key-2:
        required: false
        type: string
        default: ''
      default_endpoint:
        type: string
        description: "Destination to send telemetry to, not including path like /v1/traces"
      traceparent:
        type: string
        description: |
            Opentelemetry traceparent. Format is described in https://medium.com/@mesutatasoy/understanding-traceparent-and-microservices-in-opentelemetry-notepad-series-7-de5c16bf6462
            Generally, 00-<trace_id 32 chars>-<span_id 16 chars>-01
    # the use of secrets in shared-workflows is discouraged, especially for public repositories.
    # these values were added for situations where the use of secrets is unavoidable.
    secrets:
      RAPIDS_AUX_SECRET_1:
        required: false


permissions:
  actions: read
  checks: none
  contents: read
  deployments: none
  discussions: none
  id-token: write
  issues: none
  packages: read
  pages: none
  pull-requests: read
  repository-projects: none
  security-events: none
  statuses: none

env:
  TOP_LEVEL_TRACEPARENT: ${{ inputs.traceparent }}
  OTEL_EXPORTER_OTLP_ENDPOINT: "${{ inputs.default_endpoint }}"
  OTEL_EXPORTER_OTLP_PROTOCOL: "http/protobuf"
  OTEL_EXPORTER_OTLP_HEADERS: ${{ secrets.OTEL_EXPORTER_OTLP_HEADERS }}
  OTEL_EXPORTER_OTLP_CERTIFICATE: "/tmp/certs/ca.crt"
  OTEL_EXPORTER_OTLP_CLIENT_CERTIFICATE: "/tmp/certs/client.crt"
  OTEL_EXPORTER_OTLP_CLIENT_KEY: "/tmp/certs/client.key"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        arch: ${{ fromJSON(inputs.arch) }}
        cuda: ${{ fromJSON(inputs.cuda) }}
        pkgr: ${{ fromJSON(inputs.python_package_manager) }}
    runs-on: "linux-${{ matrix.arch }}-${{ inputs.node_type }}"
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repo }}
          ref: ${{ inputs.sha }}
          fetch-depth: 0
      - name: Check if repo has devcontainer
        run: |
          echo "REPOSITORY=$(basename $(pwd))" | tee -a "${GITHUB_ENV}";
          if test -f .devcontainer/cuda${{ matrix.cuda }}-${{ matrix.pkgr }}/devcontainer.json; then
            echo "HAS_DEVCONTAINER=true" >> "${GITHUB_ENV}";
          else
            echo "HAS_DEVCONTAINER=false" >> "${GITHUB_ENV}";
          fi
      - if: ${{ env.HAS_DEVCONTAINER == 'true' }}
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}
          role-duration-seconds: 43200 # 12h
      - if: ${{ env.HAS_DEVCONTAINER == 'true' }}
        name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - if: ${{ env.HAS_DEVCONTAINER == 'true' }}
        name: Run build in devcontainer
        uses: devcontainers/ci@v0.3
        with:
          push: never
          configFile: .devcontainer/cuda${{ matrix.cuda }}-${{ matrix.pkgr }}/devcontainer.json
          env: |
            REPOSITORY=${{ env.REPOSITORY }}
            SCCACHE_REGION=${{ vars.AWS_REGION }}
            AWS_ACCESS_KEY_ID=${{ env.AWS_ACCESS_KEY_ID }}
            AWS_SESSION_TOKEN=${{ env.AWS_SESSION_TOKEN }}
            AWS_SECRET_ACCESS_KEY=${{ env.AWS_SECRET_ACCESS_KEY }}
            RAPIDS_AUX_SECRET_1=${{ secrets.RAPIDS_AUX_SECRET_1 }}
          runCmd: |
            set -e;
            mkdir -p ~/.config/pip/;
            cat <<EOF >> ~/.config/pip/pip.conf
            [global]
            extra-index-url = https://pypi.anaconda.org/rapidsai-wheels-nightly/simple
            EOF

            rapids-make-${PYTHON_PACKAGE_MANAGER}-env;

            if test -n '${{ inputs.extra-repo-deploy-key }}' \
            || test -n '${{ inputs.extra-repo-deploy-key-2 }}'; then
              if ! pgrep ssh-agent >/dev/null 2>&1; then eval "$(ssh-agent -s)"; fi;
              if test -n '${{ inputs.extra-repo-deploy-key }}'; then
                ssh-add - <<< '${{ secrets[inputs.extra-repo-deploy-key] }}';
              fi
              if test -n '${{ inputs.extra-repo-deploy-key-2 }}'; then
                ssh-add - <<< '${{ secrets[inputs.extra-repo-deploy-key-2] }}';
              fi
              devcontainer-utils-init-ssh-deploy-keys || true;
            fi

            cd ~/"${REPOSITORY}";
            ${{ inputs.build_command }}

    # TODO: otel-cli needs to be installed. This action tries to do so, but can't write to  /usr/local/bin.
    #   The right way to install it is probably a feature, and that would be a PR to the devcontainers repo.
    #   - name: Telemetry summary
    #     id: telemetry-summary
    #     if: "always()"
    #     uses: rapidsai/shared-actions/telemetry-summarize@add-telemetry
    #     with:
    #       endpoint: ${{ inputs.default_endpoint }}
    #       traceparent: "${{ inputs.traceparent }}"