on:
  workflow_call:
    inputs:
      files_yaml:
        type: string
        required: true
      changed_files_transform_expr:
        type: string
        required: false
        default: |
          to_entries |
          map(
            select(.key | endswith("_any_changed")) |
            {
              "key": (.key | rtrimstr("_any_changed")),
              "value": (.value == "true"),
            }
          ) |
          from_entries
      force_ci_run_label:
        type: string
        required: false
        default: ""
    outputs:
      changed_file_groups:
        value: ${{ jobs.changed-files.outputs.changed_file_groups }}
      force_ci_run:
        value: ${{ jobs.changed-files.outputs.force_ci_run }}

defaults:
  run:
    shell: bash

permissions:
  actions: read
  checks: none
  contents: read
  deployments: none
  discussions: none
  id-token: write
  issues: none
  packages: read
  pages: none
  pull-requests: read
  repository-projects: none
  security-events: none
  statuses: none

jobs:
  changed-files:
    runs-on: ubuntu-latest
    name: "Check changed files"
    outputs:
      changed_file_groups: ${{ steps.transform-output.outputs.changed-file-groups }}
      force_ci_run: ${{ steps.transform-output.outputs.force-ci-run }}
    steps:
      - name: Get PR info
        id: get-pr-info
        uses: nv-gha-runners/get-pr-info@main
      - name: Checkout code repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Calculate merge base
        id: calculate-merge-base
        env:
          PR_SHA: ${{ fromJSON(steps.get-pr-info.outputs.pr-info).head.sha }}
          BASE_SHA: ${{ fromJSON(steps.get-pr-info.outputs.pr-info).base.sha }}
        run: |
          (echo -n "merge-base="; git merge-base "$BASE_SHA" "$PR_SHA") | tee --append "$GITHUB_OUTPUT"
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
          base_sha: ${{ steps.calculate-merge-base.outputs.merge-base }}
          sha: ${{ fromJSON(steps.get-pr-info.outputs.pr-info).head.sha }}
          files_yaml: ${{ inputs.files_yaml }}
      - name: Transform changed files into output
        id: transform-changed-files
        env:
          CHANGED_FILES: ${{ toJSON(steps.changed-files.outputs) }}
          CHANGED_FILES_TRANSFORM_EXPR: ${{ inputs.changed_files_transform_expr }}
          FORCE_CI_RUN_LABEL: ${{ inputs.force_ci_run_label }}
          PR_INFO_LABELS: ${{ toJSON(fromJSON(steps.get-pr-info.outputs.pr-info).labels) }}
        run: |
          (echo -n "changed-file-groups="; jq -c -n "env.CHANGED_FILES | fromjson | $CHANGED_FILES_TRANSFORM_EXPR") | tee --append "$GITHUB_OUTPUT"
          (echo -n "force-ci-run="; jq -c -n "env.FORCE_CI_RUN_LABEL != "" and (env.PR_INFO_LABELS | fromjson | any(.name == env.FORCE_CI_RUN_LABEL))") | tee --append "$GITHUB_OUTPUT"
