on:
  workflow_call:
    inputs:
      dependency_generator_config_file_path:
        description: "Location of the dependencies.yaml configuration file"
        default: "dependencies.yaml"
        required: false
        type: string
      enable_check_size:
        description: "Whether to enable the size checker"
        default: true
        type: boolean
        required: false
      enable_check_style:
        description: "Whether to enable the style checker"
        default: true
        type: boolean
        required: false
      enable_check_generated_files:
        description: "Whether to enable the generated files checker"
        default: true
        type: boolean
        required: false
      enable_check_pr_job_dependencies:
        description: "Whether to enable the PR workflow dependency checker"
        default: true
        type: boolean
        required: false
      ignored_pr_jobs:
        description: "Space separated list of jobs to ignore when checking PR workflow dependencies"
        default: ""
        type: string
        required: false
      default_endpoint:
        type: string
        description: "Destination to send telemetry to, not including path like /v1/traces"
      traceparent:
        type: string
        description: |
            Opentelemetry traceparent. Format is described in https://medium.com/@mesutatasoy/understanding-traceparent-and-microservices-in-opentelemetry-notepad-series-7-de5c16bf6462
            Generally, 00-<trace_id 32 chars>-<span_id 16 chars>-01
      otel_resource_attributes:
        type: string
        description: |
          Comma-separated key=value pairs used for storing additional "tags" to better identify data

defaults:
  run:
    shell: bash

env:
  TOP_LEVEL_TRACEPARENT: ${{ inputs.traceparent }}
  OTEL_EXPORTER_OTLP_ENDPOINT: "${{ inputs.default_endpoint }}"
  OTEL_EXPORTER_OTLP_PROTOCOL: "http/protobuf"
  OTEL_EXPORTER_OTLP_HEADERS: ${{ secrets.OTEL_EXPORTER_OTLP_HEADERS }}
  OTEL_EXPORTER_OTLP_CERTIFICATE: "/tmp/certs/ca.crt"
  OTEL_EXPORTER_OTLP_CLIENT_CERTIFICATE: "/tmp/certs/client.crt"
  OTEL_EXPORTER_OTLP_CLIENT_KEY: "/tmp/certs/client.key"
  OTEL_RESOURCE_ATTRIBUTES: ${{inputs.otel_resource_attributes}}

jobs:
  other-checks:
    runs-on: ubuntu-latest
    container:
      image: rapidsai/ci-conda:latest
      env:
        RAPIDS_GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      # this only really serves to install from gha-tools and should be removed when those PRs are merged
      - name: Telemetry setup
        id: job-traceparent
        uses: rapidsai/shared-actions/telemetry-traceparent@add-telemetry
      - name: Write certificate files for mTLS
        run: |
          mkdir -p /tmp/certs
          cat << EOF > ${OTEL_EXPORTER_OTLP_CERTIFICATE}
          ${{ secrets.OTEL_EXPORTER_OTLP_CA_CERTIFICATE }}
          EOF
          cat << EOF > ${OTEL_EXPORTER_OTLP_CLIENT_CERTIFICATE}
          ${{ secrets.OTEL_EXPORTER_OTLP_CLIENT_CERTIFICATE }}
          EOF
          cat << EOF > ${OTEL_EXPORTER_OTLP_CLIENT_KEY}
          ${{ secrets.OTEL_EXPORTER_OTLP_CLIENT_KEY }}
          EOF
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get PR Info
        id: get-pr-info
        uses: nv-gha-runners/get-pr-info@main
      - name: Run rapids-size-checker
        if: ${{ inputs.enable_check_size }}
        run: rapids-size-checker
        env:
          RAPIDS_BASE_BRANCH: ${{ fromJSON(steps.get-pr-info.outputs.pr-info).base.ref }}
      - name: Check workflow file dependencies
        if: ${{ inputs.enable_check_pr_job_dependencies }}
        run: rapids-check-pr-job-dependencies "${IGNORED_JOBS}"
        env:
          IGNORED_JOBS: ${{ inputs.ignored_pr_jobs }}
      - name: Telemetry summary
        id: telemetry-summary
        if: "always()"
        uses: rapidsai/shared-actions/telemetry-summarize@add-telemetry
        with:
          traceparent: "${{ env.TOP_LEVEL_TRACEPARENT }}"



  check-style:
    if: ${{ inputs.enable_check_style }}
    runs-on: ubuntu-latest
    container:
      image: rapidsai/ci-conda:latest
    steps:
      # this only really serves to install from gha-tools and should be removed when those PRs are merged
      - name: Telemetry setup
        id: job-traceparent
        uses: rapidsai/shared-actions/telemetry-traceparent@add-telemetry
      - name: Write certificate files for mTLS
        run: |
          mkdir -p /tmp/certs
          cat << EOF > ${OTEL_EXPORTER_OTLP_CERTIFICATE}
          ${{ secrets.OTEL_EXPORTER_OTLP_CA_CERTIFICATE }}
          EOF
          cat << EOF > ${OTEL_EXPORTER_OTLP_CLIENT_CERTIFICATE}
          ${{ secrets.OTEL_EXPORTER_OTLP_CLIENT_CERTIFICATE }}
          EOF
          cat << EOF > ${OTEL_EXPORTER_OTLP_CLIENT_KEY}
          ${{ secrets.OTEL_EXPORTER_OTLP_CLIENT_KEY }}
          EOF
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get PR Info
        id: get-pr-info
        uses: nv-gha-runners/get-pr-info@main
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-0|${{ hashFiles('.pre-commit-config.yaml') }}
      - name: Run ci/check_style.sh
        run: ci/check_style.sh
        env:
          RAPIDS_BASE_BRANCH: ${{ fromJSON(steps.get-pr-info.outputs.pr-info).base.ref }}
      - name: Telemetry summary
        id: telemetry-summary
        if: "always()"
        uses: rapidsai/shared-actions/telemetry-summarize@add-telemetry
        with:
          traceparent: "${{ env.TOP_LEVEL_TRACEPARENT }}"