on:
  workflow_call:
    inputs:
      dependency_generator_config_file_path:
        description: "Location of the dependencies.yaml configuration file"
        default: "dependencies.yaml"
        required: false
        type: string
      enable_check_size:
        default: true
        type: boolean
        required: false
      enable_check_style:
        default: true
        type: boolean
        required: false
      enable_check_generated_files:
        default: true
        type: boolean
        required: false
      enable_check_pr_job_dependencies:
        default: true
        type: boolean
        required: false

defaults:
  run:
    shell: bash

jobs:
  other-checks:
    runs-on: ubuntu-latest
    container:
      image: rapidsai/ci-conda:latest
      env:
        RAPIDS_GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        env:
          GIT_TRACE_PACKET: 1
          GIT_TRACE: 1
          GIT_CURL_VERBOSE: 1
      - name: Get PR Info
        id: get-pr-info
        uses: rapidsai/shared-actions/get-pr-info@main
      - name: Run rapids-size-checker
        if: ${{ inputs.enable_check_size }}
        run: rapids-size-checker
        env:
          RAPIDS_BASE_BRANCH: ${{ fromJSON(steps.get-pr-info.outputs.pr-info).base.ref }}
      - name: Check workflow file dependencies
        if: ${{ inputs.enable_check_pr_job_dependencies }}
        run: rapids-check-pr-job-dependencies
      - name: Run rapids-dependency-file-checker
        if: ${{ inputs.enable_check_generated_files }}
        run: rapids-dependency-file-checker ${{ inputs.dependency_generator_config_file_path }}
  check-style:
    if: ${{ inputs.enable_check_style }}
    runs-on: ubuntu-latest
    container:
      image: rapidsai/ci-conda:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        env:
          GIT_TRACE_PACKET: 1
          GIT_TRACE: 1
          GIT_CURL_VERBOSE: 1
        with:
          fetch-depth: 0
      - name: Get PR Info
        id: get-pr-info
        uses: rapidsai/shared-actions/get-pr-info@main
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-0|${{ hashFiles('.pre-commit-config.yaml') }}
      - name: Run ci/check_style.sh
        run: ci/check_style.sh
        env:
          RAPIDS_BASE_BRANCH: ${{ fromJSON(steps.get-pr-info.outputs.pr-info).base.ref }}
