on:
  workflow_call:
    inputs:
      build_type:
        required: true
        type: string
      branch:
        type: string
      date:
        type: string
      sha:
        type: string
      repo:
        type: string
      skip_upload_pkgs:
        type: string
      upload_to_label:
        description: The label that should be applied to packages uploaded to Anaconda.org
        type: string
        default: main
      default_endpoint:
        type: string
        description: "Destination to send telemetry to, not including path like /v1/traces"
      traceparent:
        type: string
        description: |
            Opentelemetry traceparent. Format is described in https://medium.com/@mesutatasoy/understanding-traceparent-and-microservices-in-opentelemetry-notepad-series-7-de5c16bf6462
            Generally, 00-<trace_id 32 chars>-<span_id 16 chars>-01
      otel_resource_attributes:
        type: string
        description: |
          Comma-separated key=value pairs used for storing additional "tags" to better identify data
      shared_actions_repo:
        type: string
        description: git repo for rapidsai/shared-actions code
        default: rapidsai/shared-actions
      shared_actions_ref:
        type: string
        description: git ref of branch/tag/sha for rapidsai/shared-actions repo
        default: main

defaults:
  run:
    shell: bash

permissions:
  actions: read
  checks: none
  contents: read
  deployments: none
  discussions: none
  id-token: write
  issues: none
  packages: read
  pages: none
  pull-requests: read
  repository-projects: none
  security-events: none
  statuses: none

env:
  OTEL_EXPORTER_OTLP_ENDPOINT: "${{ inputs.default_endpoint }}"
  OTEL_EXPORTER_OTLP_PROTOCOL: "http/protobuf"
  OTEL_PYTHON_DISABLED_INSTRUMENTATIONS: "jinja2"
  OTEL_RESOURCE_ATTRIBUTES: ${{inputs.otel_resource_attributes}}

jobs:
  upload:
    runs-on: linux-amd64-cpu4
    container:
      image: rapidsai/ci-conda:latest
      env:
        RAPIDS_BUILD_TYPE: ${{ inputs.build_type }}
    steps:
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}
          role-duration-seconds: 43200 # 12h
      - uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repo }}
          ref: ${{ inputs.sha }}
          fetch-depth: 0
      - name: Checkout actions
        uses: actions/checkout@v4
        if: always()
        with:
            repository: ${{inputs.shared_actions_repo}}
            ref: ${{inputs.shared_actions_ref}}
            path: ./shared-actions
      - name: Standardize repository information
        run: |
          echo "RAPIDS_REPOSITORY=${{ inputs.repo || github.repository }}" >> "${GITHUB_ENV}"
          echo "RAPIDS_SHA=$(git rev-parse HEAD)" >> "${GITHUB_ENV}"
          echo "RAPIDS_REF_NAME=${{ inputs.branch || github.ref_name }}" >> "${GITHUB_ENV}"
          echo "RAPIDS_NIGHTLY_DATE=${{ inputs.date }}" >> "${GITHUB_ENV}"

      - name: Telemetry setup
        id: job-traceparent
        if: always()
        uses: ./shared-actions/telemetry-traceparent

      - name: Set Proper Conda Upload Token
        run: |
          RAPIDS_CONDA_TOKEN=${{ secrets.CONDA_RAPIDSAI_NIGHTLY_TOKEN }}
          if rapids-is-release-build; then
            RAPIDS_CONDA_TOKEN=${{ secrets.CONDA_RAPIDSAI_TOKEN }}
          fi
          echo "RAPIDS_CONDA_TOKEN=${RAPIDS_CONDA_TOKEN}" >> "${GITHUB_ENV}"
      - name: Upload packages
        run: rapids-upload-to-anaconda
        env:
          SKIP_UPLOAD_PKGS: ${{ inputs.skip_upload_pkgs }}
          RAPIDS_CONDA_UPLOAD_LABEL: ${{ inputs.upload_to_label }}
      - name: Telemetry summary
        id: telemetry-summary
        if: always()
        uses: ./shared-actions/telemetry-summarize
        with:
          traceparent: "${{ inputs.traceparent }}"
          ca_cert: "${{secrets.OTEL_EXPORTER_OTLP_CA_CERTIFICATE}}"
          client_cert: "${{secrets.OTEL_EXPORTER_OTLP_CLIENT_CERTIFICATE}}"
          client_key: "${{secrets.OTEL_EXPORTER_OTLP_CLIENT_KEY}}"
