on:
  workflow_call:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - run: |
          cat <<EOFFFFFF
            ${{ toJSON(needs) }}
          EOFFFFFF
      # This reusable workflow should depend on all other jobs in the calling workflow.
      - run: exit 0
