on:
  workflow_call:
    inputs:
      needs:
        required: true
        type: string

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - run: |
          cat <<EOFFFFFF
            ${{ toJSON(fromJSON(inputs.needs)) }}
          EOFFFFFF
      # This reusable workflow should depend on all other jobs in the calling workflow.
      - run: exit 0
