name: Build RAPIDS project wheels

on:
  workflow_call:
    inputs:
      package-name:
        required: true
        type: string
      package-dir:
        required: true
        type: string
      cibw-before-all:
        required: false
        type: string
        default: ''
      cibw-before-build:
        required: false
        type: string
        default: ''
      cibw-environment:
        required: false
        type: string
        default: ''
      manylinux-platform:
        required: false
        type: string
        default: 'manylinux_2_28'
      cpu-smoketest-command:
        required: true
        type: string
      gpu-smoketest-command:
        required: false
        type: string
        default: 'true'

jobs:
  wheel-build:
    name: cibuildwheel ${{ matrix.labels[2] }}
    runs-on: ${{ matrix.labels }}
    strategy:
      matrix:
        labels: [[self-hosted, linux, amd64, cpu16], [self-hosted, linux, arm64, cpu16]]
    steps:
    - name: checkout code repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # unshallow fetch for setuptools-scm

    - name: Build wheels with custom RAPIDS cibuildwheel action
      uses: rapidsai/shared-action-workflows/cibuildwheel@feat/wheel-ci-actions
      env:
        CIBW_ENVIRONMENT: "PYTHON_PACKAGE_CUDA_SUFFIX='-cuda11' ${{ inputs.cibw-environment }}"
        CIBW_VERBOSITY: "3"
      with:
        package-dir: ${{ inputs.package-dir }}
        output-dir: dist
        manylinux-platform: ${{ inputs.manylinux-platform }}
        internal-pypi-user: cibuildwheel
        internal-pypi-pass: ${{ secrets.RAPIDSAI_PYPI_CI_PASSWORD }}
        cibw-before-all: ${{ inputs.cibw-before-all }}
        cibw-before-build: ${{ inputs.cibw-before-build }}
        #build-sdist-on: "x86_64-3.8"

    - name: Download gha-tools
      run: |
        wget https://github.com/rapidsai/gha-tools/releases/latest/download/tools.tar.gz -O - | sudo tar -xz -C /usr/local/bin
        pip install awscli

    - name: Upload wheels to downloads.rapids.ai
      run: rapids-upload-wheels-to-s3 dist
      env:
        RAPIDS_PY_VER: "38_39"
        RAPIDS_BUILD_TYPE: "pull-request"
        AWS_ACCESS_KEY_ID: ${{ secrets.RAPIDSAI_GHA_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.RAPIDSAI_GHA_AWS_SECRET_ACCESS_KEY }}

  wheel-test:
    name: wheel smoketest ${{ matrix.labels[2] }}
    runs-on: ${{ matrix.labels }}
    needs: wheel-build
    strategy:
      matrix:
        labels: [[self-hosted, linux, amd64, cpu4], [self-hosted, linux, arm64, cpu4]]
    steps:
    - name: Download gha-tools
      run: |
        wget https://github.com/rapidsai/gha-tools/releases/latest/download/tools.tar.gz -O - | sudo tar -xz -C /usr/local/bin
        pip install awscli

    - name: Download wheels from downloads.rapids.ai
      run: rapids-download-wheels-from-s3 ./dist
      env:
        RAPIDS_BUILD_TYPE: "pull-request"
        RAPIDS_PY_VER: "38_39"
        AWS_ACCESS_KEY_ID: ${{ secrets.RAPIDSAI_GHA_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.RAPIDSAI_GHA_AWS_SECRET_ACCESS_KEY }}

    - name: Run wheel smoketests for Python 3.8
      uses: rapidsai/shared-action-workflows/citestwheel@feat/wheel-ci-actions
      env:
        RAPIDS_PY_VER: 3.8
      with:
        wheel-dir: $(pwd)/dist
        wheel-filename-pattern: "${{ inputs.package-name }}_cuda11*-cp${RAPIDS_PY_VER/./}-cp${RAPIDS_PY_VER/./}-${{ inputs.manylinux-platform }}"
        cpu-smoketest-command: ${{ inputs.cpu-smoketest-command }}
        gpu-smoketest-command: ${{ inputs.gpu-smoketest-command }}

    - name: Run wheel smoketests for Python 3.9
      uses: rapidsai/shared-action-workflows/citestwheel@feat/wheel-ci-actions
      env:
        RAPIDS_PY_VER: 3.9
      with:
        wheel-dir: $(pwd)/dist
        wheel-filename-pattern: "${{ inputs.package-name }}_cuda11*-cp${RAPIDS_PY_VER/./}-cp${RAPIDS_PY_VER/./}-${{ inputs.manylinux-platform }}"
        cpu-smoketest-command: ${{ inputs.cpu-smoketest-command }}
        gpu-smoketest-command: ${{ inputs.gpu-smoketest-command }}

    - name: Publish wheels to RAPIDS internal PyPI
      run: |
        pip install twine
        twine upload ./dist/*.whl
      env:
        TWINE_USERNAME: cibuildwheel
        TWINE_PASSWORD: ${{ secrets.RAPIDSAI_PYPI_CI_PASSWORD }}
        TWINE_REPOSITORY_URL: "https://pypi.k8s.rapids.ai/simple/"
