name: Project - Get Item ID Within the Project
# This workflow gets the project-specific ID for an item within a project
# All downstream queries and mutations of fields within the project require this ID

on:
  workflow_call:
    inputs:
      PROJECT_ID:
        description: "The Project's graphQL node ID"
        type: string
        required: true

      ITEM_NODE_ID:
        description: "The issue or PR's graphQL node ID"
        type: string
        required: true

    secrets:
      PROJECT_MANAGEMENT_SECRET:
        description: "Project Access Token"
        required: true

    outputs:
      ITEM_PROJECT_ID:
        description: "The item's project-specific ID"
        value: ${{ jobs.get_items_project_id.outputs.ITEM_PROJECT_ID }}

jobs:
  get_items_project_id:
    runs-on: ubuntu-latest
    outputs:
      ITEM_PROJECT_ID: ${{ steps.get_item_id.outputs.ITEM_PROJECT_ID }}

    steps:
      - name: Sleep 1s
        id: sleep_1s
        run: |
          sleep 1 # Ensure the PR is added to the project before we query its ID

      - name: Get Item Project ID
        id: get_item_id
        env:
          GH_TOKEN: ${{ secrets.PROJECT_MANAGEMENT_SECRET }}
        run: |
            # Query up to 10 projects for the PR
            # There's no graphQL filter configured to query by a specific project
            # So we need to query all projects and filter the result ourselves
            gh api graphql -f query='
              query {
                node(id: "${{ inputs.ITEM_NODE_ID }}") {
                  ... on PullRequest {
                    projectItems(first: 10) {
                      nodes {
                        id
                        project {
                          id
                        }
                      }
                    }
                  }
                  ... on Issue {
                    projectItems(first: 10) {
                      nodes {
                        id
                        project {
                          id
                        }
                      }
                    }
                  }
                }
              }' > project_data.json
            
            # Use jq to do the actual filtering
            item_project_id=$(jq -r '.data.node.projectItems.nodes[] |
                              select(.project.id == "${{ inputs.PROJECT_ID }}") |
                              .id' project_data.json)
            echo "ITEM_PROJECT_ID=$item_project_id" >> $GITHUB_OUTPUT
        continue-on-error: true
