name: Build RAPIDS wheels

on:
  workflow_call:
    inputs:
      # repo and branch
      repo:
        type: string
      branch:
        type: string
      date:
        type: string
      sha:
        type: string
      build_type:
        required: true
        type: string

      # general settings
      package-name:
        required: true
        type: string

      # twine settings
      build-tag:
        required: false
        type: string
        default: ''

jobs:
  wheel-publish:
    name: wheels publish
    runs-on: ubuntu-latest
    container:
      # ctk version of the cibw container is irrelevant in the publish step
      # it's simply a launcher for twine
      image: "rapidsai/cibuildwheel:cuda-runtime-11.8.0-ubuntu20.04"
      env:
        RAPIDS_PY_WHEEL_NAME: ${{ inputs.package-name }}_cu11
        RAPIDS_PY_WHEEL_BUILD_TAG: ${{ inputs.build-tag }}
        RAPIDS_BUILD_TYPE: ${{ inputs.build_type }}
        AWS_ACCESS_KEY_ID: ${{ secrets.RAPIDSAI_GHA_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.RAPIDSAI_GHA_AWS_SECRET_ACCESS_KEY }}
        TWINE_USERNAME: cibuildwheel
        TWINE_PASSWORD: ${{ secrets.RAPIDSAI_PYPI_CI_PASSWORD }}
        TWINE_REPOSITORY_URL: "https://pypi.k8s.rapids.ai/simple/"
    steps:
    - name: Standardize repository information
      shell: bash
      run: |
        echo "RAPIDS_REPOSITORY=${{ inputs.repo || github.repository }}" | tee --append "${GITHUB_ENV}" "${GITHUB_OUTPUT}"
        sha="${{ inputs.sha }}"
        if [[ "${sha}" == "" ]]; then
          sha=$(git rev-parse HEAD)
        fi
        echo "RAPIDS_SHA=${sha}" | tee --append "${GITHUB_ENV}" "${GITHUB_OUTPUT}"
        echo "RAPIDS_REF_NAME=${{ inputs.branch || github.ref_name }}" | tee --append "${GITHUB_ENV}" "${GITHUB_OUTPUT}"
        echo "RAPIDS_NIGHTLY_DATE=${{ inputs.date }}" | tee --append "${GITHUB_ENV}" "${GITHUB_OUTPUT}"

    - name: Download wheels from downloads.rapids.ai and publish to internal PyPI
      shell: bash
      run: |
        # for pure or manylinux wheels, the [x86_64, 3.8] pair is always published
        RAPIDS_ARCH="x86_64" RAPIDS_PY_VERSION="3.8" rapids-download-wheels-from-s3 ./dist

        dl_wheel_is_manylinux=$(ls dist/*manylinux*.whl >&2 || echo "")
        if [[ "${dl_wheel_is_manylinux}" != "" ]]; then
          # this is a manylinux upload, upload them all
          RAPIDS_ARCH="x86_64" RAPIDS_PY_VERSION="3.9" rapids-download-wheels-from-s3 ./dist
          RAPIDS_ARCH="aarch64" RAPIDS_PY_VERSION="3.8" rapids-download-wheels-from-s3 ./dist
          RAPIDS_ARCH="aarch64" RAPIDS_PY_VERSION="3.9" rapids-download-wheels-from-s3 ./dist
        fi

        rapids-twine ./dist/
