name: Build RAPIDS wheels for amd64

on:
  workflow_call:
    inputs:
      package-name:
        required: true
        type: string
      package-dir:
        required: true
        type: string
      python-version:
        required: true
        type: string
      cibw-before-all:
        required: false
        type: string
        default: 'true'
      cibw-before-build:
        required: false
        type: string
        default: 'true'
      skbuild-configure-options:
        required: false
        type: string
        default: ''
      skbuild-build-options:
        required: false
        type: string
        default: ''
      cibw-test-requires:
        required: false
        type: string
        default: ''
      cibw-test-extras:
        required: false
        type: string
        default: ''
      cibw-test-command:
        required: false
        type: string
        default: ''
      gpu-smoketest:
        required: false
        type: string
        default: ''
      gpu-smoketest-before:
        required: false
        type: string
        default: 'true'
      auditwheel-skip-repair:
        required: false
        type: string
        default: 'false'

jobs:
  wheel-build-amd64:
    name: cibuildwheel amd64 ${{ inputs.python-version }}
    runs-on: [self-hosted, linux, amd64, cpu16]
    container:
      image: rapidsai/cibuildwheel:amd64
      env:
        NVIDIA_VISIBLE_DEVICES: ${{ env.NVIDIA_VISIBLE_DEVICES }} # GPU jobs must set this container env variable
        GITHUB_REPOSITORY: ${{ env.GITHUB_REPOSITORY }} # gha-tools needs these
        GITHUB_SHA: ${{ env.GITHUB_SHA }}
        GITHUB_REF_NAME: ${{ env.GITHUB_REF_NAME }}
        RAPIDS_PY_VER: ${{ inputs.python-version }}
        RAPIDS_BUILD_TYPE: "pull-request"
        RAPIDS_PY_WHEEL_NAME: ${{ inputs.package-name }}
        AWS_ACCESS_KEY_ID: ${{ secrets.RAPIDSAI_GHA_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.RAPIDSAI_GHA_AWS_SECRET_ACCESS_KEY }}
        CIBW_BUILD: ${{ inputs.cibw-build }}
        CIBW_BEFORE_BUILD_LINUX: ${{ inputs.cibw-before-build }}
        CIBW_BEFORE_ALL_LINUX: ${{ inputs.cibw-before-all }}
        AUDITWHEEL_SKIP_REPAIR: ${{ inputs.auditwheel-skip-repair }}
        SKBUILD_CONFIGURE_OPTIONS: "${{ inputs.skbuild-configure-options }} -DCMAKE_C_COMPILER_LAUNCHER=/usr/bin/sccache -DCMAKE_CXX_COMPILER_LAUNCHER=/usr/bin/sccache -DCMAKE_CUDA_COMPILER_LAUNCHER=/usr/bin/sccache"
        SKBUILD_BUILD_OPTIONS: ${{ inputs.skbuild-build-options }}
        SCCACHE_REGION: 'us-west-2'
        SCCACHE_IDLE_TIMEOUT: 32768
        SCCACHE_BUCKET: 'rapids-sccache'
        SCCACHE_S3_KEY_PREFIX: 'gha-cibw'
        PYTHON_PACKAGE_CUDA_SUFFIX: '-cuda11'
    steps:
    - name: Install private index credentials in cibuildwheel container
      run: printf 'machine pypi.k8s.rapids.ai\n\tlogin cibuildwheel\n\tpassword ${{ secrets.RAPIDSAI_PYPI_CI_PASSWORD }}\n' > ~/.netrc

    - name: checkout code repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # unshallow fetch for setuptools-scm

    - name: Run cibuildwheel
      run: /cibuildwheel.sh "${{ inputs.package-dir }}"

  wheel-gpu-test-amd64:
    name: wheel GPU test amd64 ${{ inputs.python-version }}
    runs-on: [self-hosted, linux, amd64, gpu-v100-495-1]
    needs: wheel-build-amd64
    container:
      image: rapidsai/wheelsmoketest:amd64
      env:
        NVIDIA_VISIBLE_DEVICES: ${{ env.NVIDIA_VISIBLE_DEVICES }} # GPU jobs must set this container env variable
        GITHUB_REPOSITORY: ${{ env.GITHUB_REPOSITORY }} # gha-tools needs these
        GITHUB_SHA: ${{ env.GITHUB_SHA }}
        GITHUB_REF_NAME: ${{ env.GITHUB_REF_NAME }}
        RAPIDS_PY_VER: ${{ inputs.python-version }}
        RAPIDS_BUILD_TYPE: "pull-request"
        RAPIDS_PY_WHEEL_NAME: ${{ inputs.package-name }}
        AWS_ACCESS_KEY_ID: ${{ secrets.RAPIDSAI_GHA_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.RAPIDSAI_GHA_AWS_SECRET_ACCESS_KEY }}
        RAPIDS_BEFORE_TEST_COMMANDS: ${{ inputs.gpu-smoketest-before }}
        CIBW_TEST_REQUIRES: ${{ inputs.cibw-test-requires }}
        CIBW_TEST_EXTRAS: ${{ inputs.cibw-test-extras }}
        CIBW_TEST_COMMAND: ${{ inputs.cibw-test-command }}
        RAPIDS_WHEEL_SMOKETEST_COMMAND: ${{ inputs.gpu-smoketest }}
    steps:
    - name: Install private index credentials in cibuildwheel container
      run: printf 'machine pypi.k8s.rapids.ai\n\tlogin cibuildwheel\n\tpassword ${{ secrets.RAPIDSAI_PYPI_CI_PASSWORD }}\n' > ~/.netrc

    - name: checkout code repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # unshallow fetch for setuptools-scm

    - name: Run GPU-enabled unit tests + smoketest for wheel
      run: /citestwheel.sh

  wheel-publish-amd64:
    name: wheel publish amd64 ${{ inputs.python-version }}
    needs: [wheel-build-amd64, wheel-gpu-test-amd64]
    if: |
      always() &&
      needs.wheel-build-amd64.result == 'success' &&
      (needs.wheel-gpu-test-amd64.result == 'success' || needs.wheel-gpu-test-amd64.result == 'skipped')
    runs-on: [self-hosted, linux, amd64, cpu4]
    steps:
    - name: Download gha-tools
      run: |
        wget https://github.com/rapidsai/gha-tools/releases/download/v0.0.2/tools.tar.gz -O - | sudo tar -xz -C /usr/local/bin
        pip install awscli

    - name: Download wheels from downloads.rapids.ai
      run: rapids-download-wheels-from-s3 ./dist
      env:
        RAPIDS_BUILD_TYPE: "pull-request"
        RAPIDS_PY_WHEEL_NAME: ${{ inputs.package-name }}
        RAPIDS_PY_VER: ${{ inputs.python-version }}
        AWS_ACCESS_KEY_ID: ${{ secrets.RAPIDSAI_GHA_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.RAPIDSAI_GHA_AWS_SECRET_ACCESS_KEY }}

    - name: Publish wheels to RAPIDS internal PyPI
      run: |
        pip install twine
        twine upload ./dist/"${{ inputs.package-name }}*.whl"
      env:
        TWINE_USERNAME: cibuildwheel
        TWINE_PASSWORD: ${{ secrets.RAPIDSAI_PYPI_CI_PASSWORD }}
        TWINE_REPOSITORY_URL: "https://pypi.k8s.rapids.ai/simple/"
