name: Build RAPIDS project wheels

on:
  workflow_call:
    inputs:
      package-name:
        required: true
        type: string
      package-dir:
        required: true
        type: string
      python-package-cuda-suffix:
        required: false
        type: string
        default: ''
      build-type:
        required: false
        type: string
        default: 'nightly'

      # versioneer and twine settings
      python-package-versioneer-override:
        required: false
        type: string
        default: ''
      python-package-build-tag:
        required: false
        type: string
        default: ''

      test-checkout-src:
        required: false
        type: string
        default: 'true'
      test-extras:
        required: false
        type: string
        default: ''
      test-unittest:
        required: false
        type: string
        default: ''
      test-before:
        required: false
        type: string
        default: 'true'

env:
  TWINE_USERNAME: cibuildwheel
  TWINE_PASSWORD: ${{ secrets.RAPIDSAI_PYPI_CI_PASSWORD }}
  TWINE_REPOSITORY_URL: "https://pypi.k8s.rapids.ai/simple/"

jobs:
  wheel-build:
    name: wheel build pure
    runs-on: [self-hosted, linux, amd64, cpu4]
    container:
      image: "rapidsai/cibuildwheel_x86_64"
      env:
        RAPIDS_PY_WHEEL_CUDA_SUFFIX: ${{ inputs.python-package-cuda-suffix }}

    steps:
    - name: checkout code repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # unshallow fetch for setuptools-scm
        persist-credentials: false

    - name: Build pure python wheel with pip wheel
      run: |
        versioneer_override="${{ inputs.python-package-versioneer-override }}"

        if [ "${versioneer_override}" == "" ]; then
          versioneer_override="$(rapids-pip-wheel-version ${{ inputs.package-name }}${{ inputs.python-package-cuda-suffix }})"
        fi
          
        export RAPIDS_PY_WHEEL_VERSIONEER_OVERRIDE="${versioneer_override}"
        python -m pip wheel -w ./dist ${{ inputs.package-dir }} --no-deps

    - name: Upload wheels to downloads.rapids.ai
      run: rapids-upload-wheels-to-s3 dist
      env:
        RAPIDS_PY_WHEEL_NAME: ${{ inputs.package-name }}
        RAPIDS_BUILD_TYPE: ${{ inputs.build-type }}
        RAPIDS_REPOSITORY: ${{ github.repository }}
        RAPIDS_SHA: ${{ github.sha }}
        RAPIDS_REF_NAME: ${{ github.ref_name }}
        RAPIDS_PY_VERSION: "3.8"
        AWS_ACCESS_KEY_ID: ${{ secrets.RAPIDSAI_GHA_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.RAPIDSAI_GHA_AWS_SECRET_ACCESS_KEY }}

  wheel-test:
    name: wheel test pure
    runs-on: [self-hosted, linux, amd64, gpu-v100-495-1]
    needs: wheel-build
    container:
      image: "rapidsai/citestwheel_x86_64"
      env:
        NVIDIA_VISIBLE_DEVICES: ${{ env.NVIDIA_VISIBLE_DEVICES }} # GPU jobs must set this container env variable
        RAPIDS_PY_WHEEL_NAME: ${{ inputs.package-name }}
        RAPIDS_REPOSITORY: ${{ github.repository }}
        RAPIDS_SHA: ${{ github.sha }}
        RAPIDS_REF_NAME: ${{ github.ref_name }}
        RAPIDS_CPYTHON_VERSION: "cp38"
        RAPIDS_BUILD_TYPE: ${{ inputs.build-type }}
        AWS_ACCESS_KEY_ID: ${{ secrets.RAPIDSAI_GHA_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.RAPIDSAI_GHA_AWS_SECRET_ACCESS_KEY }}
        RAPIDS_BEFORE_TEST_COMMANDS_AMD64: ${{ inputs.test-before }}
        CIBW_TEST_EXTRAS: ${{ inputs.test-extras }}
        CIBW_TEST_COMMAND: ${{ inputs.test-unittest }}
    steps:
    - name: Run nvidia-smi to make sure GPU is working
      run: nvidia-smi

    - name: Install private index credentials in cibuildwheel container
      run: printf 'machine pypi.k8s.rapids.ai\n\tlogin cibuildwheel\n\tpassword ${{ secrets.RAPIDSAI_PYPI_CI_PASSWORD }}\n' > ~/.netrc

    - name: checkout code repo
      uses: actions/checkout@v3
      if: ${{ inputs.test-checkout-src == 'true' }}
      with:
        fetch-depth: 0 # unshallow fetch for setuptools-scm
        persist-credentials: false

    - name: Run citestwheel
      run: /citestwheel.sh

  wheel-publish:
    name: wheel publish pure
    needs: wheel-test
    runs-on: [self-hosted, linux, amd64, cpu4]
    container:
      image: rapidsai/cibuildwheel_x86_64
      env:
        RAPIDS_PY_WHEEL_NAME: ${{ inputs.package-name }}
        RAPIDS_PY_WHEEL_BUILD_TAG: ${{ inputs.python-package-build-tag }}
        RAPIDS_REPOSITORY: ${{ github.repository }}
        RAPIDS_SHA: ${{ github.sha }}
        RAPIDS_REF_NAME: ${{ github.ref_name }}
        RAPIDS_BUILD_TYPE: ${{ inputs.build-type }}
        AWS_ACCESS_KEY_ID: ${{ secrets.RAPIDSAI_GHA_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.RAPIDSAI_GHA_AWS_SECRET_ACCESS_KEY }}

    steps:
    - name: Download wheels from downloads.rapids.ai and publish to internal PyPI
      run: |
        RAPIDS_PY_VERSION="3.8" rapids-download-wheels-from-s3 ./dist
        rapids-twine ./dist/
