name: Build RAPIDS project wheels

on:
  workflow_call:
    inputs:
      package-name:
        required: true
        type: string
      package-dir:
        required: true
        type: string
      cibw-test-requires:
        required: false
        type: string
        default: ''
      cibw-test-extras:
        required: false
        type: string
        default: ''
      cibw-test-command:
        required: false
        type: string
        default: ''
      gpu-smoketest:
        required: false
        type: string
        default: ''
      gpu-smoketest-before:
        required: false
        type: string
        default: 'true'

jobs:
  wheel-build:
    name: wheel build pure
    runs-on: [self-hosted, linux, amd64, cpu4]
    steps:
    - name: checkout code repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # unshallow fetch for setuptools-scm
        persist-credentials: false

    - name: Build pure python wheel with pip
      uses: rapidsai/shared-action-workflows/purewheel@feat/wheel-ci-actions
      with:
        package-dir: ${{ inputs.package-dir }}
        output-dir: dist
        repo-dir: ./

    - name: Download gha-tools
      run: |
        wget https://github.com/rapidsai/gha-tools/releases/download/v0.0.2/tools.tar.gz -O - | sudo tar -xz -C /usr/local/bin
        pip install awscli

    - name: Upload wheels to downloads.rapids.ai
      run: rapids-upload-wheels-to-s3 dist
      env:
        RAPIDS_BUILD_TYPE: "pull-request"
        RAPIDS_PY_WHEEL_NAME: ${{ inputs.package-name }}
        RAPIDS_PY_VER: "3.8"
        AWS_ACCESS_KEY_ID: ${{ secrets.RAPIDSAI_GHA_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.RAPIDSAI_GHA_AWS_SECRET_ACCESS_KEY }}

  wheel-test:
    name: wheel test pure
    runs-on: [self-hosted, linux, amd64, gpu-v100-495-1]
    needs: wheel-build
    continue-on-error: true # to always trigger wheel-publish
    container:
      image: rapidsai/manylinux_2_31_x86_64
      env:
        NVIDIA_VISIBLE_DEVICES: ${{ env.NVIDIA_VISIBLE_DEVICES }} # GPU jobs must set this container env variable
        GITHUB_REPOSITORY: ${{ env.GITHUB_REPOSITORY }} # gha-tools needs these
        GITHUB_SHA: ${{ env.GITHUB_SHA }}
        GITHUB_REF_NAME: ${{ env.GITHUB_REF_NAME }}
        RAPIDS_PY_VER: "3.8"
        RAPIDS_BUILD_TYPE: "pull-request"
        RAPIDS_PY_WHEEL_NAME: ${{ inputs.package-name }}
        AWS_ACCESS_KEY_ID: ${{ secrets.RAPIDSAI_GHA_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.RAPIDSAI_GHA_AWS_SECRET_ACCESS_KEY }}
        RAPIDS_BEFORE_TEST_COMMANDS_AMD64: ${{ inputs.gpu-smoketest-before }}
        CIBW_TEST_REQUIRES: ${{ inputs.cibw-test-requires }}
        CIBW_TEST_EXTRAS: ${{ inputs.cibw-test-extras }}
        CIBW_TEST_COMMAND: ${{ inputs.cibw-test-command }}
        RAPIDS_WHEEL_SMOKETEST_COMMAND: ${{ inputs.gpu-smoketest }}
        RAPIDS_WHEEL_VER_OVERRIDE: "py3-none-any" # for a pure wheel
    steps:
    - name: Run nvidia-smi to make sure GPU is working
      run: nvidia-smi

    - name: Install private index credentials in cibuildwheel container
      run: printf 'machine pypi.k8s.rapids.ai\n\tlogin cibuildwheel\n\tpassword ${{ secrets.RAPIDSAI_PYPI_CI_PASSWORD }}\n' > ~/.netrc

    - name: checkout code repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # unshallow fetch for setuptools-scm
        persist-credentials: false

    - name: Run citestwheel
      uses: rapidsai/shared-action-workflows/citestwheel@feat/wheel-ci-actions

  wheel-publish:
    name: wheel publish pure
    needs: wheel-build
    runs-on: [self-hosted, linux, amd64, cpu4]
    steps:
    - name: Download gha-tools
      run: |
        wget https://github.com/rapidsai/gha-tools/releases/download/v0.0.2/tools.tar.gz -O - | sudo tar -xz -C /usr/local/bin
        pip install awscli

    - name: Download wheels from downloads.rapids.ai
      run: rapids-download-wheels-from-s3 ./dist
      env:
        RAPIDS_BUILD_TYPE: "pull-request"
        RAPIDS_PY_WHEEL_NAME: ${{ inputs.package-name }}
        RAPIDS_PY_VER: "3.8"
        AWS_ACCESS_KEY_ID: ${{ secrets.RAPIDSAI_GHA_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.RAPIDSAI_GHA_AWS_SECRET_ACCESS_KEY }}

    - name: Publish wheels to RAPIDS internal PyPI
      run: |
        pip install twine
        twine upload ./dist/"${{ inputs.package-name }}*.whl"
      env:
        TWINE_USERNAME: cibuildwheel
        TWINE_PASSWORD: ${{ secrets.RAPIDSAI_PYPI_CI_PASSWORD }}
        TWINE_REPOSITORY_URL: "https://pypi.k8s.rapids.ai/simple/"
